SELECT ADMISSIONS.ADM_ID, DEPARTMENTS.DEPT_NAME, 
AVG(MEASUREMENTS.MEASURE_VALUE)
FROM ADMISSIONS, DEPARTMENTS, measurements
WHERE ADMISSIONS.ADM_ID=MEASUREMENTS.ADM_ID
AND ADMISSIONS.DEPT_ID=DEPARTMENTS.DEPT_ID
GROUP BY DEPARTMENTS.dept_name;